"use client";
/* Scholarly Ledger style: country research pack with paper-atlas framing, clear cost signals, and compact local programme ledger. */
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, CircleDollarSign, GraduationCap, Landmark, MapPinned, Plane } from 'lucide-react';
import { ProgramTable } from '@/components/program-table';
import { countryPacks, getCountryPack, programs } from '@/lib/mock-data';

function Stat({ icon: Icon, label, value }: { icon: typeof CircleDollarSign; label: string; value: string }) { return <div className="ledger-card p-5"><Icon className="h-5 w-5 text-primary" /><p className="mt-5 data-label">{label}</p><p className="mt-1 text-sm font-bold leading-6">{value}</p></div>; }

export default function CountryPage({ code }: { code: string }) {
  const country = getCountryPack(code ?? '');
  if (!country) return <div className="container py-12"><h1 className="text-2xl font-extrabold">Country pack not found</h1><Link href="/search" className="mt-4 inline-flex text-sm font-bold text-primary">Return to search</Link></div>;
  const countryPrograms = programs.filter((program) => program.country === country.name);
  return <div className="soft-enter"><section className="relative overflow-hidden border-b border-border bg-card"><div className="absolute inset-0 bg-gradient-to-br from-primary/[0.07] via-transparent to-accent/[0.06]" /><div className="container relative py-7 pb-12 lg:py-10 lg:pb-16"><Link href="/search" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4" />Back to search</Link><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><div><div className="flex items-center gap-3"><span className="text-4xl" role="img" aria-label={country.name}>{country.flagEmoji}</span><p className="data-label">Country pack · sample data for prototype</p></div><h1 className="mt-3 text-4xl font-extrabold tracking-tight">{country.name}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-muted-foreground">{country.visaNotes}</p></div><div className="overflow-hidden rounded-xl border border-border bg-card/95 shadow-sm backdrop-blur"><div className="border-l-4 border-primary px-5 pt-5"><p className="data-label">English-taught availability</p><div className="mt-3 flex items-end justify-between"><p className="text-2xl font-extrabold text-primary">{country.englishTaughtAvailability}</p><p className="text-xs text-muted-foreground">Sample meter</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{ width: country.englishTaughtAvailability === 'HIGH' ? '88%' : country.englishTaughtAvailability === 'MEDIUM' ? '58%' : '32%' }} /></div></div><p className="mt-4 border-t border-border px-5 py-4 text-xs leading-5 text-muted-foreground">Availability does not mean eligibility. Continue to programme language evidence.</p></div></div></div></section>
  <div className="container py-8 pb-14"><div className="grid gap-4 md:grid-cols-3"><Stat icon={CircleDollarSign} label="Tuition norms" value={country.tuitionNorms} /><Stat icon={Landmark} label="Living cost · sample" value={`€${country.livingCostMonthlyEur.low} low · €${country.livingCostMonthlyEur.avg} average / month`} /><Stat icon={BriefcaseBusiness} label="Part-time rules" value={country.partTimeRules} /></div>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1fr_.8fr]"><div className="ledger-card p-5"><p className="data-label">Scholarship ecosystem</p><div className="mt-4 space-y-3">{country.majorScholarships.map((item) => <div key={item} className="flex items-center justify-between rounded-lg border border-border bg-secondary/30 px-4 py-3"><span className="text-sm font-bold">{item}</span><ArrowUpRight className="h-4 w-4 text-primary" /></div>)}</div><p className="mt-5 text-xs leading-5 text-muted-foreground">These are sample pointers, not availability claims. Funding eligibility changes by year and applicant route.</p></div><div className="ledger-card p-5"><p className="data-label">Research timeline notes</p><ol className="mt-4 space-y-5 border-l border-primary/30 pl-5"><li><p className="text-sm font-bold">First pass · 4–8 months out</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Use {country.applicationPlatform} and programme pages to map proof requirements.</p></li><li><p className="text-sm font-bold">Funding pass · before course deadlines</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Separate scholarship calendars from admission calendars; they may not align.</p></li><li><p className="text-sm font-bold">Visa pass · after offers</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Confirm document, insurance, and funds requirements with official authorities.</p></li></ol></div></section>
    <section className="mt-8"><div className="mb-5 flex items-end justify-between"><div><p className="data-label">Local ledger</p><h2 className="mt-1 text-xl font-extrabold">Top sample programmes</h2></div><Link href="/results" className="text-sm font-bold text-primary">Full results</Link></div><ProgramTable rows={countryPrograms.slice(0, 5)} compact /></section></div></div>;
}
