"use client";
/* Scholarly Ledger style: a focused joint-programme register with mobility cues, partner chips, and an explicit full-funding filter. */
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Globe2, Route, ToggleLeft, ToggleRight } from 'lucide-react';
import { DeadlineBadge, FundingBadge } from '@/components/status-badge';
import type { ProgramRow } from '@/lib/types';

export default function ErasmusPage({ rows }: { rows: ProgramRow[] }) {
  const [onlyFunded, setOnlyFunded] = useState(false);
  const jointRows = useMemo(() => rows.filter((program) => program.isJointProgram && (!onlyFunded || ['FULLY_FUNDED', 'FULLY_FUNDED_STIPEND'].includes(program.fundingClass))), [rows, onlyFunded]);
  return <div className="container soft-enter py-8 pb-14 lg:py-10"><section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="grid gap-5 p-6 lg:grid-cols-[1fr_.8fr]"><div><div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1.5 text-xs font-bold text-primary"><Globe2 className="h-3.5 w-3.5" />Joint degree pathways</div><h1 className="mt-4 text-3xl font-extrabold tracking-tight sm:text-4xl">Erasmus Mundus, as a mobility-aware ledger.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">Joint Master’s programmes involving more than one institution and mobility destination, compared by funding, partners, and timing.</p></div><div className="rounded-xl bg-secondary p-5"><Route className="h-5 w-5 text-primary" /><p className="mt-4 text-sm font-extrabold">Mobility register</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{jointRows.length} joint programme{jointRows.length === 1 ? '' : 's'} in the researched dataset. Partner lists fill in as research runs verify them.</p></div></div></section>
    <div className="mt-7 flex items-center justify-between rounded-xl border border-border bg-card px-4 py-3"><div><p className="text-sm font-bold">Fully funded only</p><p className="text-xs text-muted-foreground">Filters the joint-programme register.</p></div><button type="button" aria-label="Toggle fully funded only" onClick={() => setOnlyFunded((value) => !value)} className="text-primary">{onlyFunded ? <ToggleRight className="h-8 w-8" /> : <ToggleLeft className="h-8 w-8 text-muted-foreground" />}</button></div>
    {jointRows.length === 0 ? <div className="ledger-card mt-5 flex min-h-60 flex-col items-center justify-center p-8 text-center"><Globe2 className="h-7 w-7 text-primary" /><h3 className="mt-4 text-lg font-extrabold">No joint programmes yet</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">Run a research pass — joint (Erasmus Mundus style) programmes appear here once verified.</p></div> : <div>
    <div className="mt-5 hidden overflow-x-auto rounded-xl border border-border bg-card md:block"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-secondary/40 text-[11px] font-bold uppercase tracking-[0.11em] text-muted-foreground"><tr><th className="px-4 py-3">Programme</th><th className="px-4 py-3">Partners</th><th className="px-4 py-3">Mobility</th><th className="px-4 py-3">Funding</th><th className="px-4 py-3">Deadline</th><th className="px-4 py-3"></th></tr></thead><tbody>{jointRows.map((program) => <tr key={program.id} className="ledger-row"><td className="px-4 py-4"><p className="font-bold">{program.program}</p><p className="mt-1 text-xs text-muted-foreground">{program.university}</p></td><td className="px-4 py-4"><div className="flex flex-wrap gap-1.5">{(program.fieldTags ?? []).map((tag) => <span key={tag} className="rounded-md border border-border px-2 py-1 text-[11px] font-semibold">{tag}</span>)}</div></td><td className="px-4 py-4 text-xs text-muted-foreground">{program.city || program.country}</td><td className="px-4 py-4"><FundingBadge funding={program.fundingClass} /></td><td className="px-4 py-4"><DeadlineBadge status={program.deadlineStatus} days={program.daysRemaining} /></td><td className="px-4 py-4"><Link href={`/programs/${program.id}`} aria-label={`Inspect ${program.program}`}><ArrowUpRight className="h-4 w-4 text-primary" /></Link></td></tr>)}</tbody></table></div>
    <div className="mt-5 space-y-3 md:hidden">{jointRows.map((program) => <Link key={program.id} href={`/programs/${program.id}`} className="ledger-card block p-4"><p className="font-bold">{program.program}</p><p className="mt-1 text-xs text-muted-foreground">{program.university}</p><div className="mt-4 flex items-center justify-between"><FundingBadge funding={program.fundingClass} /><DeadlineBadge status={program.deadlineStatus} days={program.daysRemaining} /></div></Link>)}</div></div>}
  </div>;
}
