"use client";
/* EuropaGrad style: a restrained dark academic intelligence landing surface with indigo action hierarchy, layered panels, and source-led data signals. */
import Link from 'next/link';
import { ArrowRight, CalendarClock, CheckCircle2, FileSearch, GraduationCap, SearchCheck, ShieldCheck } from 'lucide-react';
import { countryPacks, programs } from '@/lib/mock-data';
import { ProgramTable } from '@/components/program-table';

const values = [
  { icon: ShieldCheck, title: 'Every fact is sourced & dated', body: 'Inspect sample evidence entries, source tiers, excerpts, and retrieval dates in every detailed record.' },
  { icon: SearchCheck, title: 'MOI / no-IELTS filtering', body: 'Separate accepted, excluded, and unknown language-proof signals so uncertainty does not disappear.' },
  { icon: CalendarClock, title: 'Deadline intelligence', body: 'Open, approaching, future, closed, and unknown states remain visible wherever you compare decisions.' },
];

export default function Home() {
  return <div className="soft-enter">
    <section className="relative overflow-hidden border-b border-border bg-card">
      <div className="absolute inset-0 bg-gradient-to-bl from-primary/20 via-transparent to-accent/10" />
      <div className="absolute inset-0 bg-gradient-to-r from-background via-background/98 to-background/84" />
      <div className="container relative grid min-h-[440px] items-center gap-10 py-12 lg:grid-cols-[1.05fr_.95fr] lg:py-14">
        <div className="max-w-2xl">
          <div className="flex items-center gap-3"><span className="dossier-stamp"><span className="h-1.5 w-1.5 bg-emerald-600" />Sample data</span><span className="marginal-note">Dossier 01 / 2026</span></div>
          <p className="mt-5 data-label">European Master’s funding research, restructured</p>
          <h1 className="mt-3 max-w-xl text-4xl font-extrabold tracking-[-0.04em] text-foreground sm:text-5xl">Find your funded Master’s in Europe.</h1>
          <p className="mt-5 max-w-lg text-base leading-7 text-muted-foreground">Compare funding, language routes, tuition, deadlines, and evidence in one deliberately structured research workspace.</p>
          <div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/search" className="inline-flex items-center justify-center gap-2 rounded bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground shadow-sm transition-transform active:scale-[0.98]">Build your search <ArrowRight className="h-4 w-4" /></Link><Link href="/results" className="inline-flex items-center justify-center gap-2 rounded border border-border bg-card/80 px-5 py-3.5 text-sm font-bold text-foreground backdrop-blur transition-colors hover:bg-secondary">Browse sample results</Link></div>
          <p className="mt-5 border-l border-primary/70 pl-3 text-xs leading-5 text-muted-foreground">This is a strictly presentational prototype. No records are live; re-verify every fact before applying.</p>
        </div>
        <div className="hidden justify-self-end lg:block"><div className="w-80 overflow-hidden rounded-lg border border-border bg-card/95 shadow-[0_20px_55px_rgba(0,0,0,.3)] backdrop-blur"><div className="border-l-2 border-primary px-5 py-4"><div className="flex items-center justify-between"><div><p className="data-label">Evidence sheet 01</p><p className="mt-1 text-sm font-extrabold">Current sample set</p></div><FileSearch className="h-5 w-5 text-primary" /></div></div><div className="grid grid-cols-3 divide-x divide-border py-5 text-center"><div><p className="tabular text-2xl font-extrabold text-primary">{programs.length}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">Programmes</p></div><div><p className="tabular text-2xl font-extrabold text-emerald-500">9</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">Funding routes</p></div><div><p className="tabular text-2xl font-extrabold text-amber-500">6</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">Deadline states</p></div></div><div className="border-t border-border bg-secondary/50"><div className="grid grid-cols-[1fr_auto] gap-3 px-5 py-3"><div><p className="data-label">Active evidence rule</p><p className="mt-1 text-xs font-semibold text-foreground">Every material claim holds a source tier and retrieval date.</p></div><span className="self-center rounded-md border border-primary/30 bg-primary/10 px-2 py-1 text-[10px] font-bold text-primary">TIER 1</span></div><div className="border-t border-border px-5 py-3"><p className="data-label">Live sample ledger</p><div className="mt-2 space-y-2">{programs.slice(0, 2).map((program) => <div key={program.id} className="flex items-center justify-between gap-3 text-[11px]"><span className="truncate font-semibold">{program.university}</span><span className="tabular text-muted-foreground">{program.score}</span></div>)}</div></div></div></div></div>
      </div>
    </section>

    <section className="container py-12 sm:py-16"><div className="flex items-end justify-between gap-6"><div><p className="data-label">Start with a country pack</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight sm:text-3xl">Choose a research context.</h2></div><Link href="/search" className="hidden text-sm font-bold text-primary sm:inline-flex sm:items-center sm:gap-1">All Europe <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{countryPacks.map((country) => <Link key={country.code} href={`/countries/${country.code}`} className="ledger-card group min-h-32 p-4 transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><span className="text-2xl" role="img" aria-label={country.name}>{country.flagEmoji}</span><p className="mt-4 font-extrabold">{country.name}</p><p className="mt-1 text-xs text-muted-foreground">English taught: {country.englishTaughtAvailability.toLowerCase()}</p></Link>)}<Link href="/search" className="ledger-card flex min-h-32 flex-col justify-between bg-primary p-4 text-primary-foreground transition-transform hover:-translate-y-0.5"><GraduationCap className="h-5 w-5" /><p className="font-extrabold">All Europe <ArrowRight className="mt-1 h-4 w-4" /></p></Link></div></section>

    <section className="border-y border-border bg-secondary/35"><div className="container py-12 sm:py-16"><p className="data-label">How it works</p><div className="mt-5 grid gap-7 md:grid-cols-3">{['Set your evidence needs', 'Read the decision ledger', 'Move only verified choices to a plan'].map((step, index) => <div key={step} className="relative pl-12"><span className="absolute left-0 top-0 grid h-8 w-8 place-items-center rounded-md bg-card text-sm font-extrabold text-primary shadow-sm ring-1 ring-border">0{index + 1}</span><h3 className="font-extrabold">{step}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{index === 0 ? 'Set countries, funding classes, language pathways and the depth needed for this pass.' : index === 1 ? 'Use rank, score, deadline, source tier and evidence excerpts without leaving the workbench.' : 'Use the sample plan board to see how a shortlist turns into a structured application sequence.'}</p></div>)}</div></div></section>

    <section className="container py-12 sm:py-16"><div className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><div><p className="data-label">Prototype principles</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight">Research needs a traceable trail.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">The product language makes operational details easy to scan and evidence easy to challenge.</p></div><div className="grid gap-3 sm:grid-cols-3">{values.map(({ icon: Icon, title, body }, index) => <div key={title} className="ledger-card overflow-hidden"><div className="border-l-4 border-primary px-5 pt-4"><p className="data-label">Evidence rule 0{index + 1}</p><Icon className="mt-3 h-5 w-5 text-primary" /><h3 className="mt-4 font-extrabold">{title}</h3></div><p className="mt-4 border-t border-border px-5 py-4 text-sm leading-6 text-muted-foreground">{body}</p></div>)}</div></div></section>

    <section className="container pb-14"><div className="mb-5 flex items-end justify-between gap-6"><div><p className="data-label">Sample evidence ledger</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight">A funded path, at a glance.</h2></div><Link href="/results" className="text-sm font-bold text-primary">Open all results</Link></div><ProgramTable rows={programs.slice(0, 4)} compact /></section>
  </div>;
}
