"use client";
/* EuropaGrad style: a source-aware application queue rendered as a compact dark research ledger rather than a generic task board. */
import Link from 'next/link';
import { ArrowUpRight, CalendarDays, LockKeyhole, Plus, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { openAuthDialog } from '@/components/auth-dialog';
import { DeadlineBadge, FundingBadge } from '@/components/status-badge';
import { planStages, programs } from '@/lib/mock-data';

const board: Record<(typeof planStages)[number], string[]> = { Interested: ['bologna-management'], Researching: ['tu-berlin-cs'], Shortlisted: ['erasmus-big-data', 'paris-saclay-data'], Applied: [], 'Scholarship Applied': ['polimi-cs'], Result: [] };

export default function PlanPage() {
  return <div className="container soft-enter py-8 pb-14 lg:py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="data-label">Application workflow</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">My plan, modelled as a decision queue.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">This non-persistent prototype shows how a shortlist can become a clear sequence of application work.</p></div><Button variant="outline" className="gap-2"><Plus className="h-4 w-4" />Add sample item</Button></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[340px_1fr]"><aside className="space-y-4"><div className="rounded-xl border border-primary/20 bg-primary/[0.04] p-5"><div className="flex gap-3"><LockKeyhole className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-extrabold">Sign in to save a real plan</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Create a free account to keep this queue synced across devices. Sample board shown until then.</p><Button variant="outline" size="sm" className="mt-4" onClick={openAuthDialog}>Sign in with email link</Button></div></div></div><div className="ledger-card p-5"><p className="data-label">Shortlist cards</p><div className="mt-4 space-y-3">{['erasmus-big-data', 'tu-berlin-cs', 'polimi-cs'].map((id) => { const program = programs.find((item) => item.id === id); return program ? <Link key={program.id} href={`/programs/${program.id}`} className="block rounded-lg border border-border p-4 transition-colors hover:bg-secondary/50"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{program.university}</p><p className="mt-1 text-xs text-muted-foreground">{program.program}</p></div><ArrowUpRight className="h-4 w-4 text-primary" /></div><div className="mt-3 flex flex-wrap gap-2"><FundingBadge funding={program.fundingClass} /><DeadlineBadge status={program.deadlineStatus} days={program.daysRemaining} /></div></Link> : null; })}</div></div></aside>
      <section className="overflow-x-auto"><div className="mb-3 flex min-w-[1060px] items-center justify-between border-b border-border pb-3"><div><p className="data-label">Application queue ledger</p><p className="mt-1 text-xs text-muted-foreground">Each stage retains a visible funding, deadline, and source-review signal.</p></div><span className="rounded-md border border-primary/30 bg-primary/10 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-primary">Sample queue</span></div><div className="flex min-w-[1060px] gap-3">{planStages.map((stage, stageIndex) => <div key={stage} className="w-44 shrink-0"><div className="mb-3 border-l-2 border-primary bg-secondary px-3 py-3"><div className="flex items-center justify-between gap-2"><span className="text-xs font-extrabold">{stage}</span><span className="rounded-full bg-card px-2 py-0.5 tabular text-[11px] font-bold text-muted-foreground">{board[stage].length}</span></div><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Stage 0{stageIndex + 1}</p></div><div className="min-h-[300px] space-y-3 rounded-lg border border-dashed border-border bg-secondary/20 p-2">{board[stage].length === 0 ? <div className="grid min-h-24 place-items-center p-3 text-center text-xs leading-5 text-muted-foreground">No sample item here yet.</div> : board[stage].map((id) => { const program = programs.find((item) => item.id === id); return program ? <div key={program.id} className="overflow-hidden rounded-lg border border-border bg-card shadow-sm"><div className="border-l-2 border-primary px-3 pt-3"><p className="text-xs font-extrabold leading-5">{program.university}</p><p className="mt-1 text-[11px] leading-4 text-muted-foreground">{program.program}</p></div><div className="mt-3 flex items-center justify-between border-t border-border bg-secondary/45 px-3 py-2"><DeadlineBadge status={program.deadlineStatus} days={program.daysRemaining} /><span className="tabular text-[10px] font-bold text-primary">{program.score}</span></div><div className="border-t border-border px-3 py-2"><p className="text-[10px] font-semibold text-muted-foreground">Funding review</p><div className="mt-1"><FundingBadge funding={program.fundingClass} /></div></div></div> : null; })}</div></div>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">Drag-and-drop is represented visually only in this static prototype. Deadline and funding signals remain present across every queue stage.</p></section></div>
  </div>;
}
