"use client";
/* Scholarly Ledger style: an inspectable programme dossier with score signal, tabbed evidence sheets, and explicit uncertainty banners. */
import Link from 'next/link';
import { ArrowLeft, CalendarDays, CheckCircle2, ExternalLink, FileWarning, Info, Languages, Plus, ShieldAlert, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { EvidenceTable } from '@/components/evidence-table';
import { DeadlineBadge, FundingBadge, MatchPill } from '@/components/status-badge';
import { ScoreRing } from '@/components/score-ring';
import type { EvidenceEntry, ProgramRow } from '@/lib/types';
import { toast } from 'sonner';
import { createBrowserClient } from '@supabase/ssr';

async function addToPlan(programId: string) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) {
    toast.error('Storage not configured.');
    return;
  }
  const supabase = createBrowserClient(url, key);
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    toast.error('Sign in to save programmes to your plan.');
    return;
  }
  const resp = await fetch('/api/plan/saved', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ entityType: 'PROGRAM', entityId: programId }),
  });
  if (resp.ok) toast.success('Added to your plan board.');
  else toast.error('Could not save — try again.');
}

function Field({ label, value }: { label: string; value: string }) { return <div className="border-b border-border py-3 last:border-b-0"><p className="data-label">{label}</p><p className="mt-1 text-sm font-semibold leading-6">{value}</p></div>; }

export default function ProgramDetailPage({ program, evidence }: { program: ProgramRow; evidence: EvidenceEntry[] }) {
  return <div className="container soft-enter py-7 pb-14 lg:py-10"><Link href="/results" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4" />Back to results</Link>
    <header className="mt-5 overflow-hidden rounded-2xl border border-border bg-card"><div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[auto_1fr_auto] lg:items-center">{program.score != null ? <ScoreRing score={program.score} /> : <div className="grid h-24 w-24 place-items-center rounded-full border-2 border-dashed border-border text-center text-[10px] font-bold uppercase leading-4 text-muted-foreground">score<br />pending</div>}<div><div className="flex flex-wrap items-center gap-2"><FundingBadge funding={program.fundingClass} />{program.isJointProgram && <span className="rounded bg-violet-100 px-2 py-1 text-[11px] font-bold text-violet-800 dark:bg-violet-950 dark:text-violet-200">Joint programme</span>}</div><h1 className="mt-3 text-2xl font-extrabold tracking-tight sm:text-3xl">{program.program}</h1><p className="mt-1 text-base font-semibold text-muted-foreground">{program.university} · {program.city ? `${program.city}, ` : ''}{program.country}</p><div className="mt-4 flex flex-wrap gap-2"><DeadlineBadge status={program.deadlineStatus} days={program.daysRemaining} />{program.matchClass && <MatchPill match={program.matchClass} />}<span className="rounded-md bg-secondary px-2 py-1 text-[11px] font-bold text-secondary-foreground">{program.durationMonths ? `${program.durationMonths} months` : 'Duration not specified'} · {program.language}</span></div></div><Button className="gap-2" onClick={() => void addToPlan(program.id)}><Plus className="h-4 w-4" />Add to plan</Button></div><div className="border-t border-border bg-secondary/35 px-5 py-3 text-xs text-muted-foreground sm:px-7">Evidence-cited record · requirement claims must be re-verified at their official source.</div></header>
    {program.id === 'polimi-cs' && <div className="mt-5 flex gap-3 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm leading-6 text-amber-950 dark:border-amber-900 dark:bg-amber-950/35 dark:text-amber-200"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0" /><p><strong>Conflict to reconcile.</strong> This sample profile intentionally pairs a merit award with a general tuition figure. Treat scholarship coverage as conditional until the award call is confirmed.</p></div>}
    {program.id === 'tu-berlin-cs' && <div className="mt-5 flex gap-3 rounded-xl border border-sky-300 bg-sky-50 p-4 text-sm leading-6 text-sky-950 dark:border-sky-900 dark:bg-sky-950/35 dark:text-sky-200"><FileWarning className="mt-0.5 h-5 w-5 shrink-0" /><p><strong>Needs re-verification.</strong> The MOI indicator is sample-only; language-proof policies may change by intake and programme route.</p></div>}
    <Tabs defaultValue="academic" className="mt-7"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-xl border border-border bg-card p-1"><TabsTrigger value="academic">Academic</TabsTrigger><TabsTrigger value="funding">Funding</TabsTrigger><TabsTrigger value="language">Language</TabsTrigger><TabsTrigger value="deadlines">Deadlines</TabsTrigger><TabsTrigger value="work">Work</TabsTrigger><TabsTrigger value="links">Links</TabsTrigger></TabsList>
      <TabsContent value="academic" className="mt-4 ledger-card p-5"><div className="grid gap-6 md:grid-cols-2"><div><p className="data-label">Academic profile</p><Field label="Degree" value={program.degree} /><Field label="Duration" value={program.durationMonths ? `${program.durationMonths} months` : 'Not specified'} /><Field label="Fields" value={program.fieldTags.length ? program.fieldTags.join(' · ') : 'Not specified'} /></div><div><p className="data-label">Fit signal</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Match scoring is calculated by the ranking engine once your profile is set. It weighs funding alignment, tuition, language compatibility, and deadline timing.</p></div></div></TabsContent>
      <TabsContent value="funding" className="mt-4 ledger-card p-5"><div className="grid gap-6 md:grid-cols-[1fr_.8fr]"><div><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-primary" /><h2 className="font-extrabold">Funding route</h2></div><p className="mt-3 text-sm leading-6 text-muted-foreground">This record is labelled <strong>{program.fundingClass.replaceAll('_', ' ').toLowerCase()}</strong> in the sample dataset. Funding labels are decision aids, not award confirmations.</p><div className="mt-5 rounded-lg border border-border bg-secondary/30 p-4"><p className="data-label">Linked scholarship</p><p className="mt-1 font-bold">{program.scholarshipName ?? 'No linked scholarship in sample data'}</p></div></div><div className="rounded-xl bg-primary p-5 text-primary-foreground"><p className="data-label !text-primary-foreground/70">Tuition signal</p><p className="mt-2 tabular text-3xl font-extrabold">{program.tuitionEurPerYear === null ? '—' : program.tuitionEurPerYear === 0 ? '€0' : `€${program.tuitionEurPerYear.toLocaleString('en-US')}`}</p><p className="mt-1 text-sm text-primary-foreground/80">sample annual tuition</p></div></div></TabsContent>
      <TabsContent value="language" className="mt-4 ledger-card p-5"><div className="flex items-start gap-3 rounded-lg border border-primary/20 bg-primary/[0.04] p-4"><Languages className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-extrabold">Language-proof callout</p><p className="mt-1 text-sm leading-6 text-muted-foreground">IELTS sample requirement: <strong>{program.ieltsOverall ?? 'not specified'}</strong>. MOI status: <strong>{program.moiAccepted === true ? 'may be accepted' : program.moiAccepted === false ? 'not shown as accepted' : 'not specified'}</strong>.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Field label="Teaching language" value={program.language} /><Field label="TOEFL" value="Verify programme-specific equivalent" /><Field label="MOI documentation" value={program.moiAccepted === true ? 'Present in sample profile' : 'Reconfirm directly'} /></div></TabsContent>
      <TabsContent value="deadlines" className="mt-4 ledger-card p-5"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-border p-5"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" /><h2 className="font-extrabold">Programme deadline</h2></div><p className="mt-5 tabular text-2xl font-extrabold">{program.deadline ?? 'Not published'}</p><div className="mt-3"><DeadlineBadge status={program.deadlineStatus} days={program.daysRemaining} /></div></div><div className="rounded-xl border border-border p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-primary" /><h2 className="font-extrabold">Scholarship timing</h2></div><p className="mt-5 text-sm leading-6 text-muted-foreground">The linked scholarship uses its own call and can close earlier or later than programme admission. Check its dedicated evidence entry before sequencing applications.</p></div></div></TabsContent>
      <TabsContent value="work" className="mt-4 ledger-card p-5"><p className="data-label">Part-time work signal</p><p className="mt-2 text-xl font-extrabold">{program.partTimeWork.replaceAll('_', ' ').toLowerCase()}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">This is a prototype category only. Work permissions can depend on permit type, employer requirements, term time, and local regulations.</p></TabsContent>
      <TabsContent value="links" className="mt-4 ledger-card p-5"><p className="data-label">Official follow-up links</p><div className="mt-4 flex flex-wrap gap-3"><a href="https://www.study.eu/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Programme source <ExternalLink className="h-4 w-4" /></a><a href="https://erasmus-plus.ec.europa.eu/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-bold">Funding source <ExternalLink className="h-4 w-4" /></a></div></TabsContent>
    </Tabs>
    <section className="mt-8"><div className="mb-4"><p className="data-label">Source trace</p><h2 className="mt-1 text-xl font-extrabold">Evidence entries</h2></div><EvidenceTable entries={evidence} /></section>
    <section className="mt-8 border-l-2 border-primary pl-5"><p className="data-label">Change history · sample timeline</p><ol className="mt-3 space-y-3"><li className="text-sm"><strong>26 Aug 2026</strong><span className="text-muted-foreground"> · Prototype evidence record retrieved.</span></li><li className="text-sm"><strong>18 Aug 2026</strong><span className="text-muted-foreground"> · Deadline status categorised for research review.</span></li><li className="text-sm"><strong>04 Aug 2026</strong><span className="text-muted-foreground"> · Funding label attached in sample dataset.</span></li></ol></section>
  </div>;
}
