"use client";
/* Scholarly Ledger style: scholarship dossier with a practical eligibility matrix, benefit register, and linked programme evidence. */
import Link from 'next/link';
import { ArrowLeft, CalendarDays, Check, CircleHelp, ExternalLink, X } from 'lucide-react';
import { EvidenceTable } from '@/components/evidence-table';
import { DeadlineBadge, FundingBadge } from '@/components/status-badge';
import { evidenceByScholarship, getScholarship, programs } from '@/lib/mock-data';

function MatrixItem({ label, value }: { label: string; value: boolean | 'UNKNOWN' }) { const state = value === true ? 'yes' : value === false ? 'no' : 'unknown'; return <div className="flex items-center justify-between border-b border-border py-3 last:border-b-0"><span className="text-sm font-medium">{label}</span><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-bold ${state === 'yes' ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300' : state === 'no' ? 'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300' : 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300'}`}>{state === 'yes' ? <Check className="h-3.5 w-3.5" /> : state === 'no' ? <X className="h-3.5 w-3.5" /> : <CircleHelp className="h-3.5 w-3.5" />}{state === 'yes' ? 'Yes' : state === 'no' ? 'No' : 'Reconfirm'}</span></div>; }

export default function ScholarshipDetailPage({ id }: { id: string }) {
  const scholarship = getScholarship(id ?? '');
  if (!scholarship) return <div className="container py-12"><h1 className="text-2xl font-extrabold">Scholarship not found</h1><Link href="/results" className="mt-4 inline-flex text-sm font-bold text-primary">Return to results</Link></div>;
  const matches = programs.filter((program) => program.scholarshipName?.toLowerCase().includes(scholarship.name.split(' ')[0].toLowerCase()) || (scholarship.id === 'erasmus-mundus' && program.isJointProgram));
  return <div className="container soft-enter py-7 pb-14 lg:py-10"><Link href="/results" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4" />Back to sample results</Link><header className="mt-5 overflow-hidden rounded-2xl border border-border bg-card"><div className="grid gap-5 p-6 md:grid-cols-[1fr_auto]"><div><p className="data-label">{scholarship.providerType.replaceAll('_', ' ')}</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">{scholarship.name}</h1><p className="mt-2 text-sm font-semibold text-muted-foreground">{scholarship.providerName}</p><p className="mt-5 max-w-2xl text-sm leading-6 text-muted-foreground">{scholarship.competitivenessNote}</p></div><div className="rounded-xl bg-primary p-5 text-primary-foreground"><p className="data-label !text-primary-foreground/70">Sample stipend</p><p className="mt-2 tabular text-3xl font-extrabold">{scholarship.stipendMonthlyEur ? `€${scholarship.stipendMonthlyEur}` : 'Varies'}</p><p className="mt-1 text-xs text-primary-foreground/75">monthly, if shown</p></div></div><div className="flex flex-wrap items-center gap-3 border-t border-border bg-secondary/35 px-6 py-3"><DeadlineBadge status={scholarship.deadlineStatus} /><span className="text-xs text-muted-foreground">Deadline: {scholarship.deadline ?? 'not shown'}</span><span className="ml-auto text-[11px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Sample data for prototype</span></div></header>
    <section className="mt-7 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="ledger-card p-5"><p className="data-label">Benefit breakdown</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-secondary p-4"><p className="text-xs font-bold text-muted-foreground">Coverage</p><p className="mt-2 text-sm font-extrabold">{scholarship.amountSummary}</p></div><div className="rounded-lg bg-secondary p-4"><p className="text-xs font-bold text-muted-foreground">Tuition logic</p><p className="mt-2 text-sm font-extrabold">Provider and programme dependent</p></div><div className="rounded-lg bg-secondary p-4"><p className="text-xs font-bold text-muted-foreground">Application route</p><p className="mt-2 text-sm font-extrabold">{scholarship.separateApplication ? 'Separate application' : 'Programme-managed'}</p></div></div></div><div className="ledger-card p-5"><p className="data-label">Deadline card</p><div className="mt-4 flex items-center gap-3"><CalendarDays className="h-5 w-5 text-primary" /><div><p className="tabular text-lg font-extrabold">{scholarship.deadline ?? 'Future call pending'}</p><DeadlineBadge status={scholarship.deadlineStatus} /></div></div><a href="https://erasmus-plus.ec.europa.eu/" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Check provider source <ExternalLink className="h-4 w-4" /></a></div></section>
    <section className="mt-7 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="ledger-card p-5"><p className="data-label">Eligibility matrix</p><div className="mt-3"><MatrixItem label="Bangladesh nationality" value={scholarship.bangladeshEligible} /><MatrixItem label="Admission first" value={scholarship.requiresAdmissionFirst} /><MatrixItem label="Separate application" value={scholarship.separateApplication} /><MatrixItem label="Field-specific call" value="UNKNOWN" /><MatrixItem label="GPA threshold stated" value="UNKNOWN" /></div></div><div className="ledger-card overflow-hidden"><div className="border-b border-border p-5"><p className="data-label">Cross-matched programmes</p><p className="mt-1 text-sm text-muted-foreground">Sample programme links that expose this scholarship route.</p></div><div className="divide-y divide-border">{matches.length > 0 ? matches.map((program) => <Link key={program.id} href={`/programs/${program.id}`} className="flex items-center justify-between gap-4 p-4 transition-colors hover:bg-secondary/50"><div><p className="font-bold">{program.program}</p><p className="mt-1 text-xs text-muted-foreground">{program.university} · {program.country}</p></div><FundingBadge funding={program.fundingClass} /></Link>) : <div className="p-5 text-sm text-muted-foreground">No direct title match in the prototype. Use the full provider call to verify eligible programmes.</div>}</div></div></section>
    <section className="mt-8"><div className="mb-4"><p className="data-label">Source trace</p><h2 className="mt-1 text-xl font-extrabold">Evidence entries</h2></div><EvidenceTable entries={evidenceByScholarship[scholarship.id] ?? []} /></section>
  </div>;
}
