"use client";
/* Nocturne Ledger style: a high-contrast academic profile form with explicit evidence filters and a persistent next-action bar. */
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, ChevronRight, CircleHelp, Filter, GraduationCap, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';

type Mode = 'SINGLE' | 'MULTI' | 'EUROPE' | 'BEST_FOR_ME';
const modes: Array<{ id: Mode; title: string; text: string }> = [{ id: 'SINGLE', title: 'Single country', text: 'One focused application context.' }, { id: 'MULTI', title: 'Multiple', text: 'Choose a compact country set.' }, { id: 'EUROPE', title: 'All Europe', text: 'Compare across sample records.' }, { id: 'BEST_FOR_ME', title: 'Best countries for me', text: 'Use preference-weighted discovery.' }];
const depth = [{ id: 'L1', label: 'L1 Quick', text: 'Broad sample scan' }, { id: 'L2', label: 'L2 Standard', text: 'Evidence-led shortlist' }, { id: 'L3', label: 'L3 Exhaustive', text: 'Deep application review' }];

export default function SearchPage() {
  const router = useRouter();
  const [mode, setMode] = useState<Mode>('EUROPE');
  const [moi, setMoi] = useState(false);
  const [noIelts, setNoIelts] = useState(false);
  const [joint, setJoint] = useState(false);
  const [selectedDepth, setSelectedDepth] = useState('L2');
  return <div className="container soft-enter max-w-[1200px] py-8 pb-28 lg:py-12"><div className="grid gap-8 lg:grid-cols-[1fr_300px]"><div><p className="data-label">Search protocol</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">Design your evidence pass.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">This form is a presentational prototype. Use it to explore the product’s search logic; all output remains sample data.</p>
    <section className="mt-8"><div className="flex items-center gap-2"><Filter className="h-4 w-4 text-primary" /><h2 className="font-extrabold">1. Search scope</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{modes.map((item) => <button type="button" key={item.id} onClick={() => setMode(item.id)} className={`rounded-xl border p-4 text-left transition-colors ${mode === item.id ? 'border-primary bg-primary/[0.04] ring-1 ring-primary' : 'border-border bg-card hover:bg-secondary/60'}`}><div className="flex items-center justify-between"><p className="font-bold">{item.title}</p>{mode === item.id && <span className="grid h-5 w-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="h-3.5 w-3.5" /></span>}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.text}</p></button>)}</div></section>
    <section className="mt-8 border-t border-border pt-8"><div className="flex items-center gap-2"><GraduationCap className="h-4 w-4 text-primary" /><h2 className="font-extrabold">2. Academic profile</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="major">Current / prior major</Label><Select defaultValue="cs"><SelectTrigger id="major"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cs">Computer Science</SelectItem><SelectItem value="engineering">Engineering</SelectItem><SelectItem value="business">Business & management</SelectItem><SelectItem value="economics">Economics</SelectItem><SelectItem value="environment">Environment & policy</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="cgpa">CGPA (sample input)</Label><Input id="cgpa" placeholder="e.g. 3.62 / 4.00" /></div><div className="space-y-2"><Label htmlFor="grad">Graduation year</Label><Input id="grad" inputMode="numeric" placeholder="e.g. 2025" /></div><div className="space-y-2"><Label htmlFor="ielts">IELTS overall</Label><Input id="ielts" inputMode="decimal" disabled={moi} placeholder={moi ? 'MOI toggle is on' : 'e.g. 6.5'} /></div></div><div className="mt-4 flex flex-wrap gap-5 rounded-lg border border-border bg-secondary/35 px-4 py-3"><div className="flex items-center gap-2"><Switch id="moi" checked={moi} onCheckedChange={setMoi} /><Label htmlFor="moi" className="text-sm font-semibold">I have an MOI letter</Label></div><div className="flex items-center gap-2"><Switch id="no-ielts" checked={noIelts} onCheckedChange={setNoIelts} /><Label htmlFor="no-ielts" className="text-sm font-semibold">Show no-IELTS paths</Label></div></div></section>
    <section className="mt-8 border-t border-border pt-8"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-primary" /><h2 className="font-extrabold">3. Evidence filters</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div className="ledger-card p-4"><p className="data-label">Funding conditions</p><div className="mt-3 space-y-3">{['Fully funded', 'Tuition-free', 'Scholarship-linked', 'Low tuition'].map((label) => <label key={label} className="flex items-center gap-2 text-sm font-medium"><Checkbox />{label}</label>)}</div></div><div className="ledger-card p-4"><p className="data-label">Practical conditions</p><div className="mt-3 space-y-3"><label className="flex items-center gap-2 text-sm font-medium"><Checkbox />Part-time work is required</label><label className="flex items-center gap-2 text-sm font-medium"><Checkbox />Next available intake</label><label className="flex items-center gap-2 text-sm font-medium"><Checkbox checked={joint} onCheckedChange={(checked) => setJoint(checked === true)} />Joint programmes only</label></div></div></div></section>
    <section className="mt-8 border-t border-border pt-8"><div className="flex items-center gap-2"><CircleHelp className="h-4 w-4 text-primary" /><h2 className="font-extrabold">4. Research depth</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{depth.map((item) => <button type="button" onClick={() => setSelectedDepth(item.id)} key={item.id} className={`rounded border p-4 text-left ${selectedDepth === item.id ? 'border-primary bg-primary/[0.08] ring-1 ring-primary' : 'border-border bg-card'}`}><p className="font-extrabold">{item.label}</p><p className="mt-3 text-xs leading-5 text-muted-foreground">{item.text}</p></button>)}</div></section>
  </div><aside className="hidden lg:block"><div className="sticky top-24 ledger-card p-5"><p className="data-label">Search brief</p><h2 className="mt-2 text-lg font-extrabold">Your current pass</h2><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Scope</dt><dd className="font-bold">{modes.find((item) => item.id === mode)?.title}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Language</dt><dd className="font-bold">{moi ? 'MOI shown' : noIelts ? 'No-IELTS focus' : 'Any proof'}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Depth</dt><dd className="font-bold">{selectedDepth}</dd></div></dl><p className="mt-6 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">All results demonstrate interface behaviour using the sample dataset.</p></div></aside></div>
    <div className="fixed inset-x-0 bottom-0 z-20 border-t border-border bg-card/95 px-4 py-3 backdrop-blur lg:left-60"><div className="container flex max-w-[1200px] items-center justify-between gap-4 px-0"><p className="hidden text-xs text-muted-foreground sm:block">Scope: {modes.find((item) => item.id === mode)?.title} · {selectedDepth} depth</p><Button onClick={() => router.push('/results')} className="ml-auto gap-2">View sample matches <ChevronRight className="h-4 w-4" /></Button></div></div>
  </div>;
}
