"use client";
/* Nocturne Ledger style: compact left-rail archive that makes prior research states feel saved, retrievable, and operational. */
import Link from 'next/link';
import { ArchiveRestore, ArrowUpRight, Clock3 } from 'lucide-react';
import { searchHistory } from '@/lib/mock-data';

export function SearchHistory() {
  return <section className="mt-5 overflow-hidden rounded border border-border bg-card"><div className="flex items-center justify-between border-b border-border bg-secondary/50 px-3 py-2.5"><div className="flex items-center gap-2"><ArchiveRestore className="h-3.5 w-3.5 text-primary" /><p className="data-label">Search archive</p></div><span className="tabular text-[10px] font-bold text-muted-foreground">{searchHistory.length} saved</span></div><div className="border-l-2 border-primary/70 p-2"><div className="divide-y divide-border">{searchHistory.map((entry, index) => <Link key={entry.id} href="/results" className="block border-l-2 border-l-transparent px-3 py-3 transition-colors hover:border-l-primary hover:bg-secondary/45"><div className="flex items-start justify-between gap-2"><p className="text-xs font-extrabold leading-5"><span className="mr-1.5 text-[10px] text-primary">0{index + 1}</span>{entry.name}</p><ArrowUpRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" /></div><p className="mt-1 text-[10px] leading-4 text-muted-foreground">{entry.filters}</p><div className="mt-2 flex items-center justify-between gap-2 text-[10px] text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock3 className="h-3 w-3" />{entry.savedAt}</span><span className="tabular font-bold text-foreground">{entry.resultCount} matches</span></div><p className="mt-1 truncate text-[10px] font-semibold text-primary">Top: {entry.topResult}</p></Link>)}</div></div><div className="border-t border-border px-3 py-2.5"><p className="text-[10px] leading-4 text-muted-foreground">Prototype archive data · persistence is not active.</p></div></section>;
}
