import type { CountryPack, DeadlineStatus, EvidenceEntry, FundingClass, ProgramRow, Scholarship } from './types';

export const fundingClassLabels: Record<FundingClass, string> = {
  FULLY_FUNDED: 'Fully funded',
  FULLY_FUNDED_STIPEND: 'Funded + stipend',
  TUITION_FREE: 'Tuition-free',
  TUITION_WAIVER: 'Tuition waiver',
  PARTIAL_SCHOLARSHIP: 'Partial scholarship',
  LOW_TUITION: 'Low tuition',
  SELF_FUNDED: 'Self-funded',
  RESEARCH_FUNDED: 'Research funded',
  ASSISTANTSHIP: 'Assistantship',
  NOT_SPECIFIED: 'Funding not specified',
};

export const deadlineStatusLabels: Record<DeadlineStatus, string> = {
  OPEN: 'Open',
  APPROACHING: 'Approaching',
  NOT_YET_OPEN: 'Not yet open',
  FUTURE_NOT_PUBLISHED: 'Future date pending',
  CLOSED: 'Closed',
  UNKNOWN: 'Unknown',
};

export const programs: ProgramRow[] = [
  { id: 'tu-berlin-cs', rank: 1, country: 'Germany', city: 'Berlin', university: 'TU Berlin', program: 'MSc Computer Science', degree: 'MSc', fieldTags: ['Computer Science', 'AI'], language: 'English', durationMonths: 24, tuitionEurPerYear: 0, fundingClass: 'TUITION_FREE', scholarshipName: 'DAAD EPOS', ieltsOverall: 6.5, moiAccepted: true, intake: 'Winter 2027', deadline: '2026-11-30', deadlineStatus: 'OPEN', daysRemaining: 96, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 92, isJointProgram: false },
  { id: 'rwth-data-science', rank: 2, country: 'Germany', city: 'Aachen', university: 'RWTH Aachen', program: 'MSc Data Science', degree: 'MSc', fieldTags: ['Data Science', 'Mathematics'], language: 'English', durationMonths: 24, tuitionEurPerYear: 0, fundingClass: 'FULLY_FUNDED_STIPEND', scholarshipName: 'RWTH Graduate Scholarship', ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'Winter 2027', deadline: '2026-09-18', deadlineStatus: 'APPROACHING', daysRemaining: 23, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 89, isJointProgram: false },
  { id: 'heidelberg-physics', rank: 3, country: 'Germany', city: 'Heidelberg', university: 'Heidelberg University', program: 'MSc Physics', degree: 'MSc', fieldTags: ['Physics', 'Research'], language: 'English', durationMonths: 24, tuitionEurPerYear: 0, fundingClass: 'RESEARCH_FUNDED', scholarshipName: 'Research group assistant funding', ieltsOverall: 6.5, moiAccepted: false, intake: 'Winter 2027', deadline: '2027-01-15', deadlineStatus: 'NOT_YET_OPEN', daysRemaining: 142, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 87, isJointProgram: false },
  { id: 'mannheim-econ', rank: 4, country: 'Germany', city: 'Mannheim', university: 'University of Mannheim', program: 'MSc Economic and Business Education', degree: 'MSc', fieldTags: ['Economics', 'Management'], language: 'English', durationMonths: 24, tuitionEurPerYear: 194, fundingClass: 'ASSISTANTSHIP', scholarshipName: 'Student assistant roles', ieltsOverall: 7, moiAccepted: false, intake: 'Fall 2027', deadline: '2027-02-28', deadlineStatus: 'FUTURE_NOT_PUBLISHED', daysRemaining: null, partTimeWork: 'ALLOWED', matchClass: 'POSSIBLE', score: 79, isJointProgram: false },
  { id: 'freiburg-environment', rank: 5, country: 'Germany', city: 'Freiburg', university: 'University of Freiburg', program: 'MSc Environmental Governance', degree: 'MSc', fieldTags: ['Environment', 'Policy'], language: 'English', durationMonths: 24, tuitionEurPerYear: 3000, fundingClass: 'SELF_FUNDED', scholarshipName: null, ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'Winter 2026', deadline: '2026-06-15', deadlineStatus: 'CLOSED', daysRemaining: 0, partTimeWork: 'ALLOWED', matchClass: 'POSSIBLE', score: 72, isJointProgram: false },
  { id: 'polimi-cs', rank: 6, country: 'Italy', city: 'Milan', university: 'Politecnico di Milano', program: 'MSc Computer Science and Engineering', degree: 'MSc', fieldTags: ['Computer Science', 'Engineering'], language: 'English', durationMonths: 24, tuitionEurPerYear: 3898, fundingClass: 'PARTIAL_SCHOLARSHIP', scholarshipName: 'Polimi Merit Scholarship', ieltsOverall: 6, moiAccepted: true, intake: 'September 2027', deadline: '2026-12-15', deadlineStatus: 'OPEN', daysRemaining: 111, partTimeWork: 'RESTRICTED', matchClass: 'HIGH', score: 86, isJointProgram: false },
  { id: 'bologna-management', rank: 7, country: 'Italy', city: 'Bologna', university: 'University of Bologna', program: 'International Management', degree: 'MSc', fieldTags: ['Management', 'Business'], language: 'English', durationMonths: 24, tuitionEurPerYear: 0, fundingClass: 'TUITION_WAIVER', scholarshipName: 'Unibo Action 2', ieltsOverall: 6.5, moiAccepted: true, intake: 'September 2027', deadline: '2026-10-20', deadlineStatus: 'OPEN', daysRemaining: 55, partTimeWork: 'RESTRICTED', matchClass: 'HIGH', score: 84, isJointProgram: false },
  { id: 'padua-data-science', rank: 8, country: 'Italy', city: 'Padua', university: 'University of Padua', program: 'MSc Data Science', degree: 'MSc', fieldTags: ['Data Science', 'Statistics'], language: 'English', durationMonths: 24, tuitionEurPerYear: 2600, fundingClass: 'LOW_TUITION', scholarshipName: 'Padua Excellence', ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'October 2027', deadline: '2026-11-02', deadlineStatus: 'OPEN', daysRemaining: 68, partTimeWork: 'RESTRICTED', matchClass: 'HIGH', score: 83, isJointProgram: false },
  { id: 'sapienza-ai', rank: 9, country: 'Italy', city: 'Rome', university: 'Sapienza University of Rome', program: 'MSc Artificial Intelligence and Robotics', degree: 'MSc', fieldTags: ['AI', 'Robotics'], language: 'English', durationMonths: 24, tuitionEurPerYear: 3000, fundingClass: 'NOT_SPECIFIED', scholarshipName: null, ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'October 2027', deadline: null, deadlineStatus: 'UNKNOWN', daysRemaining: null, partTimeWork: 'RESTRICTED', matchClass: 'POSSIBLE', score: 73, isJointProgram: false },
  { id: 'paris-saclay-data', rank: 10, country: 'France', city: 'Paris', university: 'Université Paris-Saclay', program: 'MSc Mathematics and Artificial Intelligence', degree: 'MSc', fieldTags: ['AI', 'Mathematics'], language: 'English', durationMonths: 24, tuitionEurPerYear: 243, fundingClass: 'FULLY_FUNDED', scholarshipName: 'Paris-Saclay International Masters Scholarship', ieltsOverall: 6.5, moiAccepted: false, intake: 'September 2027', deadline: '2026-12-01', deadlineStatus: 'OPEN', daysRemaining: 97, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 91, isJointProgram: false },
  { id: 'grenoble-engineering', rank: 11, country: 'France', city: 'Grenoble', university: 'Grenoble INP', program: 'MSc Electrical Engineering for Smart Grids', degree: 'MSc', fieldTags: ['Engineering', 'Energy'], language: 'English', durationMonths: 24, tuitionEurPerYear: 3770, fundingClass: 'PARTIAL_SCHOLARSHIP', scholarshipName: 'Eiffel Scholarship', ieltsOverall: 6.5, moiAccepted: false, intake: 'September 2027', deadline: '2026-09-30', deadlineStatus: 'APPROACHING', daysRemaining: 35, partTimeWork: 'ALLOWED', matchClass: 'POSSIBLE', score: 80, isJointProgram: false },
  { id: 'sciencespo-europe', rank: 12, country: 'France', city: 'Paris', university: 'Sciences Po', program: 'Master in European Affairs', degree: 'Master', fieldTags: ['Policy', 'Europe'], language: 'English', durationMonths: 24, tuitionEurPerYear: 15300, fundingClass: 'PARTIAL_SCHOLARSHIP', scholarshipName: 'Émile Boutmy Scholarship', ieltsOverall: 7, moiAccepted: false, intake: 'August 2027', deadline: '2026-11-26', deadlineStatus: 'OPEN', daysRemaining: 92, partTimeWork: 'RESTRICTED', matchClass: 'POSSIBLE', score: 75, isJointProgram: false },
  { id: 'tudelft-systems', rank: 13, country: 'Netherlands', city: 'Delft', university: 'TU Delft', program: 'MSc Computer and Embedded Systems Engineering', degree: 'MSc', fieldTags: ['Engineering', 'Computer Science'], language: 'English', durationMonths: 24, tuitionEurPerYear: 23800, fundingClass: 'FULLY_FUNDED', scholarshipName: 'Justus & Louise van Effen Scholarship', ieltsOverall: 6.5, moiAccepted: false, intake: 'September 2027', deadline: '2026-12-01', deadlineStatus: 'OPEN', daysRemaining: 97, partTimeWork: 'RESTRICTED', matchClass: 'HIGH', score: 88, isJointProgram: false },
  { id: 'utrecht-ai', rank: 14, country: 'Netherlands', city: 'Utrecht', university: 'Utrecht University', program: 'MSc Artificial Intelligence', degree: 'MSc', fieldTags: ['AI', 'Cognitive Science'], language: 'English', durationMonths: 24, tuitionEurPerYear: 23143, fundingClass: 'TUITION_WAIVER', scholarshipName: 'Utrecht Excellence Scholarship', ieltsOverall: 6.5, moiAccepted: false, intake: 'September 2027', deadline: '2027-01-31', deadlineStatus: 'NOT_YET_OPEN', daysRemaining: 158, partTimeWork: 'RESTRICTED', matchClass: 'HIGH', score: 85, isJointProgram: false },
  { id: 'leiden-governance', rank: 15, country: 'Netherlands', city: 'Leiden', university: 'Leiden University', program: 'MSc Crisis and Security Management', degree: 'MSc', fieldTags: ['Policy', 'Security'], language: 'English', durationMonths: 12, tuitionEurPerYear: 21500, fundingClass: 'SELF_FUNDED', scholarshipName: null, ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'September 2027', deadline: '2027-04-01', deadlineStatus: 'FUTURE_NOT_PUBLISHED', daysRemaining: null, partTimeWork: 'RESTRICTED', matchClass: 'LOW', score: 61, isJointProgram: false },
  { id: 'kth-sustainable', rank: 16, country: 'Sweden', city: 'Stockholm', university: 'KTH Royal Institute of Technology', program: 'MSc Sustainable Energy Engineering', degree: 'MSc', fieldTags: ['Energy', 'Engineering'], language: 'English', durationMonths: 24, tuitionEurPerYear: 15000, fundingClass: 'FULLY_FUNDED', scholarshipName: 'Swedish Institute Scholarship', ieltsOverall: 6.5, moiAccepted: true, intake: 'August 2027', deadline: '2027-01-15', deadlineStatus: 'NOT_YET_OPEN', daysRemaining: 142, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 90, isJointProgram: false },
  { id: 'lund-cybersecurity', rank: 17, country: 'Sweden', city: 'Lund', university: 'Lund University', program: 'MSc Information Security', degree: 'MSc', fieldTags: ['Cybersecurity', 'Computer Science'], language: 'English', durationMonths: 24, tuitionEurPerYear: 17000, fundingClass: 'PARTIAL_SCHOLARSHIP', scholarshipName: 'Lund Global Scholarship', ieltsOverall: 6.5, moiAccepted: true, intake: 'August 2027', deadline: '2027-01-15', deadlineStatus: 'NOT_YET_OPEN', daysRemaining: 142, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 82, isJointProgram: false },
  { id: 'uppsala-embedded', rank: 18, country: 'Sweden', city: 'Uppsala', university: 'Uppsala University', program: 'MSc Embedded Systems', degree: 'MSc', fieldTags: ['Engineering', 'Embedded Systems'], language: 'English', durationMonths: 24, tuitionEurPerYear: 14500, fundingClass: 'RESEARCH_FUNDED', scholarshipName: 'Department research assistant roles', ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'August 2027', deadline: '2027-01-16', deadlineStatus: 'NOT_YET_OPEN', daysRemaining: 143, partTimeWork: 'ALLOWED', matchClass: 'POSSIBLE', score: 78, isJointProgram: false },
  { id: 'stockholm-econ', rank: 19, country: 'Sweden', city: 'Stockholm', university: 'Stockholm University', program: 'MSc Economics', degree: 'MSc', fieldTags: ['Economics', 'Finance'], language: 'English', durationMonths: 24, tuitionEurPerYear: 13000, fundingClass: 'SELF_FUNDED', scholarshipName: null, ieltsOverall: 7, moiAccepted: false, intake: 'August 2026', deadline: '2026-01-15', deadlineStatus: 'CLOSED', daysRemaining: 0, partTimeWork: 'ALLOWED', matchClass: 'POSSIBLE', score: 70, isJointProgram: false },
  { id: 'erasmus-big-data', rank: 20, country: 'France', city: 'Paris', university: 'EIT Digital', program: 'Erasmus Mundus Big Data Management', degree: 'MSc', fieldTags: ['Data Science', 'Management'], language: 'English', durationMonths: 24, tuitionEurPerYear: null, fundingClass: 'FULLY_FUNDED_STIPEND', scholarshipName: 'Erasmus Mundus Joint Masters Scholarship', ieltsOverall: 6.5, moiAccepted: false, intake: 'September 2027', deadline: '2026-12-10', deadlineStatus: 'OPEN', daysRemaining: 106, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 94, isJointProgram: true },
  { id: 'erasmus-imaging', rank: 21, country: 'Netherlands', city: 'Eindhoven', university: 'Erasmus+ Consortium', program: 'Erasmus Mundus Imaging', degree: 'MSc', fieldTags: ['Imaging', 'Engineering'], language: 'English', durationMonths: 24, tuitionEurPerYear: null, fundingClass: 'FULLY_FUNDED_STIPEND', scholarshipName: 'Erasmus Mundus Joint Masters Scholarship', ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'September 2027', deadline: '2026-12-15', deadlineStatus: 'OPEN', daysRemaining: 111, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 90, isJointProgram: true },
  { id: 'nordic-environment', rank: 22, country: 'Sweden', city: 'Stockholm', university: 'Nordic Five Tech Consortium', program: 'Erasmus Mundus Environmental Engineering', degree: 'MSc', fieldTags: ['Environment', 'Engineering'], language: 'English', durationMonths: 24, tuitionEurPerYear: null, fundingClass: 'FULLY_FUNDED', scholarshipName: 'Erasmus Mundus Joint Masters Scholarship', ieltsOverall: 6.5, moiAccepted: true, intake: 'August 2027', deadline: '2026-11-15', deadlineStatus: 'OPEN', daysRemaining: 81, partTimeWork: 'ALLOWED', matchClass: 'HIGH', score: 93, isJointProgram: true },
  { id: 'helsinki-computation', rank: 23, country: 'Finland', city: 'Helsinki', university: 'University of Helsinki', program: 'MSc Data Science', degree: 'MSc', fieldTags: ['Data Science', 'Mathematics'], language: 'English', durationMonths: 24, tuitionEurPerYear: 15000, fundingClass: 'ASSISTANTSHIP', scholarshipName: 'Faculty assistantship sample', ieltsOverall: 6.5, moiAccepted: 'NOT_SPECIFIED', intake: 'August 2027', deadline: null, deadlineStatus: 'UNKNOWN', daysRemaining: null, partTimeWork: 'ALLOWED', matchClass: 'POSSIBLE', score: 77, isJointProgram: false },
];

export const scholarships: Scholarship[] = [
  { id: 'daad-epos', name: 'DAAD EPOS', providerName: 'German Academic Exchange Service', providerType: 'GOVERNMENT_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'Monthly stipend, insurance and travel support; programme-specific tuition terms apply.', stipendMonthlyEur: 992, requiresAdmissionFirst: false, separateApplication: true, competitivenessNote: 'Sample note: prioritises documented development relevance and professional experience.', deadline: '2026-11-30', deadlineStatus: 'OPEN' },
  { id: 'invest-your-talent', name: 'Invest Your Talent in Italy', providerName: 'Italian Ministry of Foreign Affairs', providerType: 'GOVERNMENT_SCHOLARSHIP', bangladeshEligible: 'UNKNOWN', amountSummary: 'Sample government grant and tuition support for selected fields.', stipendMonthlyEur: 1000, requiresAdmissionFirst: true, separateApplication: true, competitivenessNote: 'Sample note: confirm annual eligible-country list and participating institutions.', deadline: '2026-12-01', deadlineStatus: 'OPEN' },
  { id: 'eiffel', name: 'Eiffel Excellence Scholarship', providerName: 'French Ministry for Europe and Foreign Affairs', providerType: 'GOVERNMENT_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'Monthly allowance and selected services; tuition treatment depends on host institution.', stipendMonthlyEur: 1181, requiresAdmissionFirst: false, separateApplication: false, competitivenessNote: 'Sample note: the institution normally nominates applicants.', deadline: '2026-09-30', deadlineStatus: 'APPROACHING' },
  { id: 'holland-scholarship', name: 'Holland Scholarship', providerName: 'Study in NL / participating institutions', providerType: 'GOVERNMENT_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'One-time contribution toward first-year study costs.', stipendMonthlyEur: null, requiresAdmissionFirst: true, separateApplication: true, competitivenessNote: 'Sample note: limited award, confirm partner-university availability.', deadline: '2027-02-01', deadlineStatus: 'NOT_YET_OPEN' },
  { id: 'swedish-institute', name: 'Swedish Institute Scholarship for Global Professionals', providerName: 'Swedish Institute', providerType: 'GOVERNMENT_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'Tuition coverage, monthly living allowance and travel grant in sample profile.', stipendMonthlyEur: 1100, requiresAdmissionFirst: false, separateApplication: true, competitivenessNote: 'Sample note: work experience and leadership evidence are material.', deadline: '2027-02-10', deadlineStatus: 'NOT_YET_OPEN' },
  { id: 'erasmus-mundus', name: 'Erasmus Mundus Joint Masters Scholarship', providerName: 'European Commission', providerType: 'JOINT_MULTI_COUNTRY', bangladeshEligible: true, amountSummary: 'Sample full participation-cost coverage, travel support and living contribution.', stipendMonthlyEur: 1400, requiresAdmissionFirst: false, separateApplication: false, competitivenessNote: 'Sample note: one competitive joint-programme application.', deadline: '2026-12-10', deadlineStatus: 'OPEN' },
  { id: 'polimi-merit', name: 'Polimi Merit Scholarship', providerName: 'Politecnico di Milano', providerType: 'UNIVERSITY_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'Sample tuition waiver with selected annual living stipend awards.', stipendMonthlyEur: 833, requiresAdmissionFirst: false, separateApplication: false, competitivenessNote: 'Sample note: merit ranking and programme portfolio are key.', deadline: '2026-12-15', deadlineStatus: 'OPEN' },
  { id: 'paris-saclay-scholarship', name: 'Paris-Saclay International Masters Scholarship', providerName: 'Université Paris-Saclay', providerType: 'UNIVERSITY_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'Sample annual allowance; tuition treatment follows programme rules.', stipendMonthlyEur: 833, requiresAdmissionFirst: true, separateApplication: false, competitivenessNote: 'Sample note: programmes invite shortlisted applicants.', deadline: '2026-12-01', deadlineStatus: 'OPEN' },
  { id: 'kth-scholarship', name: 'KTH Scholarship', providerName: 'KTH Royal Institute of Technology', providerType: 'UNIVERSITY_SCHOLARSHIP', bangladeshEligible: true, amountSummary: 'Sample full tuition waiver for selected fee-paying students.', stipendMonthlyEur: null, requiresAdmissionFirst: true, separateApplication: true, competitivenessNote: 'Sample note: does not normally cover living costs.', deadline: '2027-01-15', deadlineStatus: 'NOT_YET_OPEN' },
];

export const countryPacks: CountryPack[] = [
  { code: 'DE', name: 'Germany', flagEmoji: '🇩🇪', tuitionNorms: 'Many public universities charge no tuition; semester fees still apply in sample profiles.', livingCostMonthlyEur: { low: 850, avg: 1150 }, partTimeRules: 'Sample guide: international students may have regulated work-day limits; check your visa conditions.', visaNotes: 'Proof-of-funds requirements should be reconfirmed before applying.', majorScholarships: ['DAAD EPOS', 'University grants', 'Research assistantships'], applicationPlatform: 'University portals and uni-assist', englishTaughtAvailability: 'HIGH' },
  { code: 'IT', name: 'Italy', flagEmoji: '🇮🇹', tuitionNorms: 'Public tuition is often income-sensitive; sample range varies materially by institution.', livingCostMonthlyEur: { low: 750, avg: 1150 }, partTimeRules: 'Sample guide: work is commonly permitted within visa conditions and local limits.', visaNotes: 'Pre-enrolment and visa workflows can involve embassy documentation.', majorScholarships: ['Invest Your Talent in Italy', 'Regional DSU grants', 'University merit awards'], applicationPlatform: 'University portals and Universitaly', englishTaughtAvailability: 'MEDIUM' },
  { code: 'FR', name: 'France', flagEmoji: '🇫🇷', tuitionNorms: 'Public degree fees may be comparatively low; differentiated fees and exemptions vary.', livingCostMonthlyEur: { low: 900, avg: 1350 }, partTimeRules: 'Sample guide: student work permissions are generally capped by annual hours.', visaNotes: 'Campus France steps may apply depending on applicant location.', majorScholarships: ['Eiffel', 'Paris-Saclay scholarship', 'Émile Boutmy'], applicationPlatform: 'University portals and Campus France', englishTaughtAvailability: 'HIGH' },
  { code: 'NL', name: 'Netherlands', flagEmoji: '🇳🇱', tuitionNorms: 'Non-EEA tuition is often substantial, so scholarship fit is especially material.', livingCostMonthlyEur: { low: 1100, avg: 1550 }, partTimeRules: 'Sample guide: work can require employer permits and is typically limited.', visaNotes: 'Housing planning is a major application-timeline consideration.', majorScholarships: ['Holland Scholarship', 'University Excellence awards', 'van Effen Scholarship'], applicationPlatform: 'Studielink and university portals', englishTaughtAvailability: 'HIGH' },
  { code: 'SE', name: 'Sweden', flagEmoji: '🇸🇪', tuitionNorms: 'Fee-paying students face programme tuition; scholarships can cover all or part in sample entries.', livingCostMonthlyEur: { low: 900, avg: 1250 }, partTimeRules: 'Sample guide: no fixed statutory student-hour cap is shown here; studies remain primary.', visaNotes: 'Residence permit maintenance requires a clear funding plan.', majorScholarships: ['Swedish Institute', 'KTH Scholarship', 'Lund Global Scholarship'], applicationPlatform: 'University Admissions Sweden', englishTaughtAvailability: 'HIGH' },
];

const sharedEvidence: EvidenceEntry[] = [
  { field: 'Data notice', value: 'Sample data for prototype', sourceUrl: 'https://www.daad.de/en/studying-in-germany/', sourceTier: 'TIER1_OFFICIAL', quote: 'This prototype uses representative sample records. Confirm every eligibility condition, amount, and deadline on the official page.', retrievedAt: '2026-08-26' },
  { field: 'Language proof', value: 'Programme-specific requirement', sourceUrl: 'https://www.tu.berlin/en/studying/applying-and-enrolling', sourceTier: 'TIER1_OFFICIAL', quote: 'Applicants must submit language documentation in the form and at the level specified for the chosen programme.', retrievedAt: '2026-08-26' },
  { field: 'Funding route', value: 'External or institutional scholarship', sourceUrl: 'https://erasmus-plus.ec.europa.eu/', sourceTier: 'TIER1_OFFICIAL', quote: 'Scholarship terms, selection procedures and participation costs are published by the relevant programme or provider.', retrievedAt: '2026-08-26' },
];

export const evidenceByProgram: Record<string, EvidenceEntry[]> = Object.fromEntries(programs.map((program) => [program.id, [
  ...sharedEvidence,
  { field: 'Programme', value: `${program.degree} · ${program.durationMonths} months · ${program.language}`, sourceUrl: 'https://www.universityadmissions.se/', sourceTier: 'TIER2_PORTAL', quote: `Sample catalogue entry for ${program.university}; always reconfirm the final course catalogue and admissions rules on the university site.`, retrievedAt: '2026-08-26' },
]]));

export const evidenceByScholarship: Record<string, EvidenceEntry[]> = Object.fromEntries(scholarships.map((scholarship) => [scholarship.id, [
  ...sharedEvidence,
  { field: 'Eligibility', value: scholarship.bangladeshEligible === true ? 'Bangladesh listed in sample profile' : scholarship.bangladeshEligible === false ? 'Bangladesh excluded in sample profile' : 'Eligibility needs reconfirmation', sourceUrl: 'https://studyin-europe.ec.europa.eu/', sourceTier: 'TIER2_PORTAL', quote: 'Sample eligibility notes are indicative only and do not substitute for the provider’s current call for applications.', retrievedAt: '2026-08-26' },
]]));

export const planStages = ['Interested', 'Researching', 'Shortlisted', 'Applied', 'Scholarship Applied', 'Result'] as const;

export const searchHistory = [
  { id: 'history-01', name: 'Funded AI · Europe', savedAt: '26 Aug 2026 · 18:42', filters: 'EU · Fully funded · MOI considered', resultCount: 8, topResult: 'Erasmus Mundus Big Data Management' },
  { id: 'history-02', name: 'Germany tuition-free', savedAt: '25 Aug 2026 · 11:18', filters: 'Germany · Tuition-free · CS', resultCount: 4, topResult: 'TU Berlin · MSc Computer Science' },
  { id: 'history-03', name: 'Sweden energy paths', savedAt: '23 Aug 2026 · 21:05', filters: 'Sweden · Sustainable energy · Scholarships', resultCount: 3, topResult: 'KTH · MSc Sustainable Energy Engineering' },
];

export const reportGroups = {
  funded: ['erasmus-big-data', 'nordic-environment', 'paris-saclay-data', 'kth-sustainable'],
  tuitionFree: ['tu-berlin-cs', 'heidelberg-physics', 'bologna-management'],
  noIelts: ['tu-berlin-cs', 'polimi-cs', 'bologna-management', 'kth-sustainable'],
  moi: ['tu-berlin-cs', 'polimi-cs', 'bologna-management', 'kth-sustainable'],
};

export const getProgram = (id: string) => programs.find((program) => program.id === id);
export const getScholarship = (id: string) => scholarships.find((scholarship) => scholarship.id === id);
export const getCountryPack = (code: string) => countryPacks.find((country) => country.code === code.toUpperCase());
